[package]
name = "terminal-size"
version = "0.1.0"
edition = "2024"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.0.1", features = ["termios"] }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
]