import type { Metadata } from "next";
import "./globals.css";
import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";
import Wrapper from "@/components/Wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`g-root g-root_theme_dark`}
            >
                <Wrapper>
                    {children}
                </Wrapper>
            </body>
        </html>
    );
}
