[package]
name = "tailborn"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.33", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "fs",
    "sync",
    "io-util",
    "io-std",
] }
thiserror = "1.0"
num_cpus = "1.16"
anyhow = "1.0"
