[package]
name = "control"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
thiserror.workspace = true
serde.workspace = true
bincode.workspace = true
network.workspace = true
tokio.workspace = true
futures.workspace = true
anyhow.workspace = true
tower.workspace = true
